# 错误处理

`try...catch` 结构允许我们处理执行过程中出现的 error。从字面上看，它允许“尝试”运行代码并“捕获”其中可能发生的 error

## “try…catch”语法

```js
try {
  // 执行此处代码
} catch (err) {
  // 如果发生 error，跳转至此处
  // err 是一个 error 对象
} finally {
  // 无论怎样都会在 try/catch 之后执行
}
```

>`try...catch` 是同步执行的，若是错误发生在异步中，则无法捕获错误
>
>这儿可能会没有 `catch` 或者没有 `finally`，所以 `try...catch` 或 `try...finally` 都是可用的

## Error 对象

发生错误时，JavaScript 会生成一个包含有关此 error 详细信息的对象。

1. Error 对象包含下列属性：
   - `message` 人类可读的 error 信息。
   - `name` 具有 error 名称的字符串（Error 构造器的名称）。
   - `stack`（没有标准，但得到了很好的支持）—— Error 发生时的调用栈。

### ”throw“ 操作符

`throw` 操作符会生成一个 error 对象。

语法如下：

```javascript
throw <error object>
```

技术上讲，我们可以将任何东西用作 error 对象。甚至可以是一个原始类型数据，例如数字或字符串，但最好使用对象，最好使用具有 `name` 和 `message` 属性的对象（某种程度上保持与内建 error 的兼容性）。

JavaScript 中有很多内建的标准 error 的构造器：`Error`，`SyntaxError`，`ReferenceError`，`TypeError` 等。我们也可以使用它们来创建 error 对象。

## 自定义Error